# This file has state objects used across the subquery agent and Aggregator graph

from typing import List, TypedDict, Dict


class SubQueryState(TypedDict):
    """
    Represents the state of our subquery agent graph.

    Attributes:
        simple_question: concise question without without a lot of complexity
        retrieved_columns_metadata: list of metadata of retrieved columns from the vector DB
        graded_columns_segments: list of retrieved columns metadata segmented in yes and no keys
        human_column_evaluation: boolean indicating if human has evaluated the column segments as correct
        pyspark_code_raw: list of generated pyspark code snippets as strings
        output_variable_names_raw: list of names of output variables the code is supposed to generate
        code_evaluation_remarks: list of remarks generated during code evaluation by llm code evaluator chain
        code_evaluation_scores: list of scores (out of 10) generated during code evaluation by llm code evaluator chain
        human_code_evaluation: boolean indicating if human has approved the generated code
        """

    simple_question: str

    retrieved_columns_metadata: List[Dict]

    graded_columns_segments: Dict[str, List[Dict]]

    human_column_evaluation: bool

    pyspark_code_raw: List[str]

    code_evaluation_remarks: List[List[str]]
    code_evaluation_scores: List[int]

    output_variable_names_raw: List[str]
    human_code_evaluation: bool



class AggregatorState(TypedDict):
    """
    Represents the state of our Aggregator graph.

    Attributes:
        final_answer: final answer generated by the LLM after processing all subquery answers
    """

    final_answer: str