# Takes generated code from last node, gives criqitue and pointers for evaluation

import pandas as pd
from typing import Any, Dict, List
from graph.state import SubQueryState
from graph.chains.code_evaluator_chain import pyspark_code_evaluator    

relational_db = pd.read_parquet("data/relational_database.parquet")

def code_evaluator_node(state: SubQueryState) -> Dict[str, Any]:
    print("---CODE EVALUATION---")
    # extract generated pyspark code from state
    pyspark_code_history = state["pyspark_code_raw"]
    latest_pyspark_code = pyspark_code_history[-1] if pyspark_code_history else ""

    # extract simple question from state
    simple_question = state["simple_question"]

    # extract required columns from state and get their details from relational_db
    graded_columns_segments = state["graded_columns_segments"]
    graded_columns_segments_yes = graded_columns_segments.get("yes", [])
    column_details_list = []
    for column_metadata in graded_columns_segments_yes:
        hash_id = column_metadata['hash_id']
        column_row = relational_db[relational_db['hash_id'] == hash_id]
        # convert the row to a string representation
        column_row = column_row.to_dict(orient='records')[0]
        column_details_list.append(column_row)
    
    print("Evaluating code: ", latest_pyspark_code)
    input_data = {
        "required_columns_data": column_details_list,
        "question": simple_question,
        "code_to_evaluate": latest_pyspark_code
    }

    response = pyspark_code_evaluator.invoke(input=input_data)
    evaluation_remarks: List[str] = response.remarks   # remarks generated by llm
    evaluation_score: int = response.score  # score out of 10
    # output_variables: List[str] = response.output_variable_names  # names of output variables the code is supposed to generate

    # If code evaluation score is more than 8, go to human code check node. Else go to pyspark code generator node some k times (5)
    return {
        "code_evaluation_remarks": state.get("code_evaluation_remarks", []) + [evaluation_remarks],
        "code_evaluation_scores": state.get("code_evaluation_scores", []) + [evaluation_score],
        # "output_variable_names_raw": state.get("output_variable_names_raw", []) + [output_variables]
    }


